version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: razaqadedeji/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD:vpropass
  
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DAFAULT_USER=guest
      - RABBITMQ_DAFAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-files/app
    image: razaqadedeji/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps


  vproweb:
    build:
      context: ./Docker-files/web
    image: razaqadedeji/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}